name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-build-test:
    name: Lint, build, test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - name: Run Biome linter
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm test
